### ISSUE TITLE
where is dependences?

### ISSUE THREAD

**Issue by martinslae** [ashortname/HikVision-Arcsoft#1]
where is CHNetSDK, gif.Component and HAF_2_0 dll?

thank you

**Comment by ashortname** [comment]
This project is very poor, it is just suitable for a reference.
By the way, the dll "gif.Component.dll" is not used, you may  delete it directly.
[dlls.zip](https://github.com/ashortname/HikVision-Arcsoft/files/3050573/dlls.zip)

**Comment by ashortname** [comment]
You may find the source code here : [Click here](https://github.com/ashortname/HikVision-Arcsoft/blob/master/README.md)
